apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  generation: 1
  labels:
    component: velero
  name: prod-old
spec:
  config:
    resourceGroup: sdpaksVeleroBackup
  provider: azure
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  generation: 1
  labels:
    component: velero
  name: prod-old
spec:
  config:
    resourceGroup: sdpaksVeleroBackup
    storageAccount: sdpaksvelerobackup
  objectStorage:
    bucket: velero
    prefix: ""
  provider: azure
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  generation: 1
  labels:
    component: velero
  name: dev-old
spec:
  config:
    resourceGroup: sdpaksDevBackup
  provider: azure
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  generation: 1
  labels:
    component: velero
  name: dev-old
spec:
  config:
    resourceGroup: sdpaksDevBackup
    storageAccount: sdpaksdevbackup
  objectStorage:
    bucket: velero-dev
    prefix: ""
  provider: azure